/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/AppProvider.vue')['default']
    BasicButton: typeof import('./src/components/BasicButton/BasicButton.vue')['default']
    BasicInput: typeof import('./src/components/BasicInput/index.vue')['default']
    ComProgressBar: typeof import('./src/components/ComProgressBar/index.vue')['default']
    ComSkeleton: typeof import('./src/components/ComSkeleton/index.vue')['default']
    Empty: typeof import('./src/components/Empty/Empty.vue')['default']
    Iconify: typeof import('./src/components/Iconify/Iconify.vue')['default']
    Link: typeof import('./src/components/Link/Link.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon/index.vue')['default']
    LogoHeader: typeof import('./src/components/LogoHeader/LogoHeader.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    PullRefreshList: typeof import('./src/components/PullRefreshList/PullRefreshList.vue')['default']
    ResourceIcon: typeof import('./src/components/ResourceIcon/ResourceIcon.vue')['default']
    ResoureIcon: typeof import('./src/components/ResourceIcon/ResoureIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test/index.vue')['default']
  }
}
