/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/AppProvider.vue')['default']
    AttendanceDetails: typeof import('./src/components/AttendanceDetails/AttendanceDetails.vue')['default']
    AttendanceState: typeof import('./src/components/AttendanceState/AttendanceState.vue')['default']
    Audio: typeof import('./src/components/mp-html/uni-app/components/mp-html/audio/audio.vue')['default']
    BadEidtor: typeof import('./src/components/BadEidtor/BadEidtor.vue')['default']
    BasicButton: typeof import('./src/components/BasicButton/BasicButton.vue')['default']
    BasicInput: typeof import('./src/components/BasicInput/index.vue')['default']
    ComProgressBar: typeof import('./src/components/ComProgressBar/index.vue')['default']
    ComSkeleton: typeof import('./src/components/ComSkeleton/index.vue')['default']
    Empty: typeof import('./src/components/Empty/Empty.vue')['default']
    ExpandContent: typeof import('./src/components/ExpandContent/ExpandContent.vue')['default']
    FilePicker: typeof import('./src/components/FilePicker/FilePicker.vue')['default']
    FilesContent: typeof import('./src/components/FilesContent/FilesContent.vue')['default']
    Iconify: typeof import('./src/components/Iconify/Iconify.vue')['default']
    LieCheckbox: typeof import('./src/components/QuizFormRender/LieCheckbox.vue')['default']
    Link: typeof import('./src/components/Link/Link.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon/LoadingIcon.vue')['default']
    LogoHeader: typeof import('./src/components/LogoHeader/LogoHeader.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MpHtml: typeof import('./src/components/mp-html/uni-app/components/mp-html/mp-html.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    Node: typeof import('./src/components/mp-html/uni-app/components/mp-html/node/node.vue')['default']
    PersonInformation: typeof import('./src/components/personInformation/index.vue')['default']
    Popup: typeof import('./src/components/Popup/Popup.vue')['default']
    PullRefreshList: typeof import('./src/components/PullRefreshList/PullRefreshList.vue')['default']
    QuizFormRender: typeof import('./src/components/QuizFormRender/QuizFormRender.vue')['default']
    RenderHtml: typeof import('./src/components/RenderHtml/RenderHtml.vue')['default']
    ResourceIcon: typeof import('./src/components/ResourceIcon/ResourceIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRoles: typeof import('./src/components/SelectRoles/SelectRoles.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar/StatusBar.vue')['default']
    TabBar: typeof import('./src/components/TabBar/TabBar.vue')['default']
    Test: typeof import('./src/components/Test/index.vue')['default']
  }
}
